---
title: "Pointblank Features: Valid VI"
author: "FISABIO"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document: 
    theme: cerulean
    highlight: breezedark
    css: style.css
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
      code_folding: "none"

---

```{css, echo=FALSE}
#header .btn-group {
    display: none;
}

```

```{r setup, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# load libraries and functions-------------------------------------------------
source(file.path("..", "scripts", "Librerias.R"))
source(file.path("..", "scripts", "Funciones.R"))
validate_rmd()

```

```{r definir_plot, echo=FALSE, warning=FALSE, message=FALSE}
# Custom ggplot2 theme---------------------------------------------------------
theme_set(theme_bw())
tema_azul <- theme_update(
  plot.background = element_rect(fill = "aliceblue", colour = "black"),
  strip.background = element_rect(colour = "black", fill = "white"))

# Define zero days-------------------------------------------------------------
zero_days = difftime(ymd("2000-01-01"), ymd("2000-01-01"), units = "days")

```

# Pointblank: VALID-VI

```{r validation_step_functions, validate = TRUE}
col_exists(small_table, columns = vars(a, b, c, d, e, f))
rows_distinct(small_table, vars(d, e))
col_vals_gt(small_table, vars(d), 1000)

```



