---
title: "Tidymodels"
output: html_document
---


```{r setup, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# Cargar librerías, funciones y Paths------------------------------------------
w_dir <- file.path( "d:", "Users", "20833717H", "Desktop", "R_Projects")
source(file.path(w_dir, "Opioids", "Scripts", "Funciones_Bases_de_Datos.R"))

```

```{r definir_plot, echo=FALSE, warning=FALSE, message=FALSE}
# definir el estilo de los gráficos--------------------------------------------
theme_set(theme_bw())
tema_azul <- theme_update(
  plot.background = element_rect(fill = "lightblue", colour = NA))

# defnir cero días-------------------------------------------------------------
zero_days = difftime(ymd("2000-01-01"), ymd("2000-01-01"), units = "days")

```

```{r}
# cargar base -----------------------------------------------------------------
library(tidymodels)  
# Helper packages
library(readr)       # for importing data
library(vip)         # for variable importance plots

hotels <- read_csv(file = file.path("datos", "hotels.csv")) %>%
  mutate_if(is.character, as.factor) 

dim(hotels)

```

```{r}
hotels %>% 
  count(children) %>% 
  mutate(prop = n/sum(n))
#> # A tibble: 2 x 3
#>   children     n   prop
#>   <fct>    <int>  <dbl>
#> 1 children  4038 0.0808
#> 2 none     45962 0.919

```

```{r}
set.seed(123)
splits      <- initial_split(hotels, strata = children)

hotel_other <- training(splits)
hotel_test  <- testing(splits)

# training set proportions by children
hotel_other %>% 
  count(children) %>% 
  mutate(prop = n/sum(n))
#> # A tibble: 2 x 3
#>   children     n   prop
#>   <fct>    <int>  <dbl>
#> 1 children  3048 0.0813
#> 2 none     34452 0.919

# test set proportions by children
hotel_test  %>% 
  count(children) %>% 
  mutate(prop = n/sum(n))
#> # A tibble: 2 x 3
#>   children     n   prop
#>   <fct>    <int>  <dbl>
#> 1 children   990 0.0792
#> 2 none     11510 0.921

```

```{r}
set.seed(234)
val_set <- validation_split(hotel_other, 
                            strata = children, 
                            prop = 0.80)
val_set
#> # Validation Set Split (0.8/0.2)  using stratification 
#> # A tibble: 1 x 2
#>   splits             id        
#>   <list>             <chr>     
#> 1 <split [30K/7.5K]> validation

```

```{r}
lr_mod <- 
  logistic_reg(penalty = tune(), mixture = 1) %>% 
  set_engine("glmnet")

```

```{r}
holidays <- c("AllSouls", "AshWednesday", "ChristmasEve", "Easter", 
              "ChristmasDay", "GoodFriday", "NewYearsDay", "PalmSunday")

lr_recipe <- 
  recipe(children ~ ., data = hotel_other) %>% 
  step_date(arrival_date) %>% 
  step_holiday(arrival_date, holidays = holidays) %>% 
  step_rm(arrival_date) %>% 
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_zv(all_predictors()) %>% 
  step_normalize(all_predictors())

```

```{r}
lr_workflow <- 
  workflow() %>% 
  add_model(lr_mod) %>% 
  add_recipe(lr_recipe)

```

```{r}
lr_reg_grid <- tibble(penalty = 10^seq(-4, -1, length.out = 30))

lr_reg_grid %>% top_n(-5) # lowest penalty values
#> Selecting by penalty
#> # A tibble: 5 x 1
#>    penalty
#>      <dbl>
#> 1 0.0001  
#> 2 0.000127
#> 3 0.000161
#> 4 0.000204
#> 5 0.000259
lr_reg_grid %>% top_n(5)  # highest penalty values
#> Selecting by penalty
#> # A tibble: 5 x 1
#>   penalty
#>     <dbl>
#> 1  0.0386
#> 2  0.0489
#> 3  0.0621
#> 4  0.0788
#> 5  0.1

```

```{r}
lr_res <- 
  lr_workflow %>% 
  tune_grid(val_set,
            grid = lr_reg_grid,
            control = control_grid(save_pred = TRUE),
            metrics = metric_set(roc_auc))

```

```{r}
lr_plot <- 
  lr_res %>% 
  collect_metrics() %>% 
  ggplot(aes(x = penalty, y = mean)) + 
  geom_point() + 
  geom_line() + 
  ylab("Area under the ROC Curve") +
  scale_x_log10(labels = scales::label_number())

lr_plot 

```

```{r}
top_models <-
  lr_res %>% 
  show_best("roc_auc", n = 15) %>% 
  arrange(penalty) 
top_models
#> # A tibble: 15 x 7
#>     penalty .metric .estimator  mean     n std_err .config              
#>       <dbl> <chr>   <chr>      <dbl> <int>   <dbl> <chr>                
#>  1 0.0001   roc_auc binary     0.880     1      NA Preprocessor1_Model01
#>  2 0.000127 roc_auc binary     0.881     1      NA Preprocessor1_Model02
#>  3 0.000161 roc_auc binary     0.881     1      NA Preprocessor1_Model03
#>  4 0.000204 roc_auc binary     0.881     1      NA Preprocessor1_Model04
#>  5 0.000259 roc_auc binary     0.881     1      NA Preprocessor1_Model05
#>  6 0.000329 roc_auc binary     0.881     1      NA Preprocessor1_Model06
#>  7 0.000418 roc_auc binary     0.881     1      NA Preprocessor1_Model07
#>  8 0.000530 roc_auc binary     0.881     1      NA Preprocessor1_Model08
#>  9 0.000672 roc_auc binary     0.881     1      NA Preprocessor1_Model09
#> 10 0.000853 roc_auc binary     0.881     1      NA Preprocessor1_Model10
#> 11 0.00108  roc_auc binary     0.881     1      NA Preprocessor1_Model11
#> 12 0.00137  roc_auc binary     0.881     1      NA Preprocessor1_Model12
#> 13 0.00174  roc_auc binary     0.881     1      NA Preprocessor1_Model13
#> 14 0.00221  roc_auc binary     0.880     1      NA Preprocessor1_Model14
#> 15 0.00281  roc_auc binary     0.879     1      NA Preprocessor1_Model15

```

```{r}
lr_best <- 
  lr_res %>% 
  collect_metrics() %>% 
  arrange(penalty) %>% 
  slice(12)
lr_best
#> # A tibble: 1 x 7
#>   penalty .metric .estimator  mean     n std_err .config              
#>     <dbl> <chr>   <chr>      <dbl> <int>   <dbl> <chr>                
#> 1 0.00137 roc_auc binary     0.881     1      NA Preprocessor1_Model12

```

```{r}
lr_auc <- 
  lr_res %>% 
  collect_predictions(parameters = lr_best) %>% 
  roc_curve(children, .pred_children) %>% 
  mutate(model = "Logistic Regression")

autoplot(lr_auc)

```

```{r}
cores <- parallel::detectCores()
cores
#> [1] 8

```

```{r}
rf_mod <- 
  rand_forest(mtry = tune(), min_n = tune(), trees = 1000) %>% 
  set_engine("ranger", num.threads = cores) %>% 
  set_mode("classification")

```

```{r}
rf_recipe <- 
  recipe(children ~ ., data = hotel_other) %>% 
  step_date(arrival_date) %>% 
  step_holiday(arrival_date) %>% 
  step_rm(arrival_date) 

```

```{r}
rf_workflow <- 
  workflow() %>% 
  add_model(rf_mod) %>% 
  add_recipe(rf_recipe)

```

```{r}
rf_mod
#> Random Forest Model Specification (classification)
#> 
#> Main Arguments:
#>   mtry = tune()
#>   trees = 1000
#>   min_n = tune()
#> 
#> Engine-Specific Arguments:
#>   num.threads = cores
#> 
#> Computational engine: ranger

# show what will be tuned
rf_mod %>%    
  parameters()  
#> Collection of 2 parameters for tuning
#> 
#>  identifier  type    object
#>        mtry  mtry nparam[?]
#>       min_n min_n nparam[+]
#> 
#> Model parameters needing finalization:
#>    # Randomly Selected Predictors ('mtry')
#> 
#> See `?dials::finalize` or `?dials::update.parameters` for more information.

```

```{r}
set.seed(345)
rf_res <- 
  rf_workflow %>% 
  tune_grid(val_set,
            grid = 25,
            control = control_grid(save_pred = TRUE),
            metrics = metric_set(roc_auc))
#> i Creating pre-processing data to finalize unknown parameter: mtry

```

```{r}
rf_res %>% 
  show_best(metric = "roc_auc")
#> # A tibble: 5 x 8
#>    mtry min_n .metric .estimator  mean     n std_err .config              
#>   <int> <int> <chr>   <chr>      <dbl> <int>   <dbl> <chr>                
#> 1     8     7 roc_auc binary     0.933     1      NA Preprocessor1_Model13
#> 2     3     3 roc_auc binary     0.933     1      NA Preprocessor1_Model21
#> 3     6    18 roc_auc binary     0.932     1      NA Preprocessor1_Model24
#> 4     7    25 roc_auc binary     0.932     1      NA Preprocessor1_Model03
#> 5     5    35 roc_auc binary     0.931     1      NA Preprocessor1_Model12

```


```{r}
autoplot(rf_res)

```

```{r}
rf_best <- 
  rf_res %>% 
  select_best(metric = "roc_auc")
rf_best
#> # A tibble: 1 x 3
#>    mtry min_n .config              
#>   <int> <int> <chr>                
#> 1     8     7 Preprocessor1_Model13

```

```{r}
rf_res %>% 
  collect_predictions()
#> # A tibble: 187,475 x 8
#>   id        .pred_children .pred_none  .row  mtry min_n children .config        
#>   <chr>              <dbl>      <dbl> <int> <int> <int> <fct>    <chr>          
#> 1 validati…       0.00247       0.998    11    12     7 none     Preprocessor1_…
#> 2 validati…       0             1        13    12     7 none     Preprocessor1_…
#> 3 validati…       0             1        31    12     7 none     Preprocessor1_…
#> 4 validati…       0.000249      1.00     32    12     7 none     Preprocessor1_…
#> 5 validati…       0.000167      1.00     36    12     7 none     Preprocessor1_…
#> # … with 187,470 more rows

```

```{r}
rf_auc <- 
  rf_res %>% 
  collect_predictions(parameters = rf_best) %>% 
  roc_curve(children, .pred_children) %>% 
  mutate(model = "Random Forest")

```

```{r}
bind_rows(rf_auc, lr_auc) %>% 
  ggplot(aes(x = 1 - specificity, y = sensitivity, col = model)) + 
  geom_path(lwd = 1.5, alpha = 0.8) +
  geom_abline(lty = 3) + 
  coord_equal() + 
  scale_color_viridis_d(option = "plasma", end = .6)

```

```{r}
# the last model
last_rf_mod <- 
  rand_forest(mtry = 8, min_n = 7, trees = 1000) %>% 
  set_engine("ranger", num.threads = cores, importance = "impurity") %>% 
  set_mode("classification")

# the last workflow
last_rf_workflow <- 
  rf_workflow %>% 
  update_model(last_rf_mod)

# the last fit
set.seed(345)
last_rf_fit <- 
  last_rf_workflow %>% 
  last_fit(splits)

last_rf_fit
#> # Resampling results
#> # Manual resampling 
#> # A tibble: 1 x 6
#>   splits         id          .metrics     .notes      .predictions     .workflow
#>   <list>         <chr>       <list>       <list>      <list>           <list>   
#> 1 <split [37.5K… train/test… <tibble [2 … <tibble [0… <tibble [12,500… <workflo…

```
```{r}
last_rf_fit %>% 
  collect_metrics()
#> # A tibble: 2 x 4
#>   .metric  .estimator .estimate .config             
#>   <chr>    <chr>          <dbl> <chr>               
#> 1 accuracy binary         0.948 Preprocessor1_Model1
#> 2 roc_auc  binary         0.922 Preprocessor1_Model1

```

```{r}
last_rf_fit %>% 
  pluck(".workflow", 1) %>%   
  pull_workflow_fit() %>% 
  vip(num_features = 20)

```

```{r}
last_rf_fit %>% 
  collect_predictions() %>% 
  roc_curve(children, .pred_children) %>% 
  autoplot()

```

